### PR TITLE
:bug: Fix scope of query selector

### PR DESCRIPTION
**Pull request by megasent1**
Fix scope of query selector for pausing/unpausing & images lazy loading + fix some e2e tests

### CODE REVIEW

**Comment by kyuwoo-choi** [comment]
🎉 thanks for the PR.

**Comment by nickolNN** [comment]
[Vue warn]: Error in mounted hook: "TypeError: this.$refs.list.$el is undefined"

found in

---> <InnerSlider>
       <VueSlickCarousel>

TypeError: "this.$refs.list.$el is undefined"
    checkImagesLoad vue-slick-carousel.umd.js:10998
    updated vue-slick-carousel.umd.js:10726
    VueJS 6

yesterday it worked ok
tried several times with/without configuration, but this behaviour is repetative and breaks the slider

**Comment by megasent1** [comment]
> [Vue warn]: Error in mounted hook: "TypeError: this.$refs.list.$el is undefined"
> 
> found in
> 
> --->
> TypeError: "this.$refs.list.$el is undefined"
> checkImagesLoad vue-slick-carousel.umd.js:10998
> updated vue-slick-carousel.umd.js:10726
> VueJS 6
> 
> yesterday it worked ok
> tried several times with/without configuration, but this behaviour is repetative and breaks the slider

Could you please provide a reproducible demo for this? Looks like carousel $refs.list element does not exist.

@kyuwoo-choi should I replace this.$refs.list.$el with this.$el as a base for querySelector?

**Comment by nickolNN** [comment]
@megasent1 don't really know what happened, but when I noticed your change I switched back to version 1.0.2, created it again and it worked without these errors, then I noticed your previous message, switched to v1.0.3 to reproduce the bug and it not reproduced, I even double-checked the package-lock and it says v1.0.3 but none of error messages appear

**Comment by kyuwoo-choi** [comment]
https://github.com/gs-shop/vue-slick-carousel/issues/91

it seems some case causes the problem.
we need to identify the case.

**Comment by disjointed** [comment]
`this.$refs.list` is not a Vue component, it's just a ref to a div. So `this.$refs.list.$el` does not make sense. It should be just `this.$refs.list` in lines [109](https://github.com/gs-shop/vue-slick-carousel/blob/5b7152a56060054c3e2354e4208d39717fd3b90e/src/InnerSlider.vue#L109) and [338](https://github.com/gs-shop/vue-slick-carousel/blob/5b7152a56060054c3e2354e4208d39717fd3b90e/src/InnerSlider.vue#L338).
I just tried modifying code locally and the errors where gone.

**Comment by haog1** [comment]
Hey the issue looks still there after installing the latest 1.0.3

My code is:
```
        <vue-slick-carousel v-bind="settings">
          <div
            v-for="repeater in feature_repeater"
            :key="repeater.feature_heading_en"
            class="repeaters__item"
          >
            <media v-if="icon" :src="icon" class="repeaters__item--icon" />
            <div class="repeaters__item--heading">
              {{ getContent(repeater, "heading") }}
            </div>
            <div class="repeaters__item--description">
              {{ getContent(repeater, "description") }}
            </div>
          </div>
        </vue-slick-carousel>
```
and the error is 
```
client.js:84 TypeError: Cannot read property 'querySelectorAll' of undefined
    at VueComponent.mounted (vue-slick-carousel.umd.js:10714)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854)
    at callHook (vue.runtime.esm.js:4219)
    at Object.insert (vue.runtime.esm.js:3139)
    at invokeInsertHook (vue.runtime.esm.js:6346)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:6565)
    at VueComponent.Vue._update (vue.runtime.esm.js:3948)
    at VueComponent.updateComponent (vue.runtime.esm.js:4060)
    at Watcher.get (vue.runtime.esm.js:4479)
    at Watcher.run (vue.runtime.esm.js:4554)
```

**Comment by megasent1** [comment]
> `this.$refs.list` is not a Vue component, it's just a ref to a div. So `this.$refs.list.$el` does not make sense. It should be just `this.$refs.list`, without ".$el" in lines [109](https://github.com/gs-shop/vue-slick-carousel/blob/5b7152a56060054c3e2354e4208d39717fd3b90e/src/InnerSlider.vue#L109) and [338](https://github.com/gs-shop/vue-slick-carousel/blob/5b7152a56060054c3e2354e4208d39717fd3b90e/src/InnerSlider.vue#L338).
> I just tried modifying code locally and the errors where gone.
> 
> Here's the [template lines](https://github.com/gs-shop/vue-slick-carousel/blob/5b7152a56060054c3e2354e4208d39717fd3b90e/src/InnerSlider.vue#L685-L700).

Yes, you are correct. I will make a PR for this. Sorry for the inconveniences.

**Comment by megasent1** [comment]
@kyuwoo-choi, please review new PR for this. 
https://github.com/gs-shop/vue-slick-carousel/pull/92

**Pull request merged**
