### PR TITLE
Change lodash to lodash.[function] (for #107)

### PR DESCRIPTION
**Pull request by ekanant**
Reference #107

Before change
|File|Size|Gzipped|
|-|:-:|-:|
|dist/vue-slick-carousel.umd.min.js|102.17 KiB|33.36 KiB|
|dist/vue-slick-carousel.umd.js|348.16 KiB|80.65 KiB|
|dist/vue-slick-carousel.common.js|347.76 KiB|80.52 KiB|
|dist/vue-slick-carousel-theme.css|4.24 KiB|1.96 KiB|
|dist/vue-slick-carousel.css|1.57 KiB|0.51 KiB|

After change
|File|Size|Gzipped|
|-|:-:|-:|
|dist/vue-slick-carousel.umd.min.js|94.77 KiB|30.95 KiB|
|dist/vue-slick-carousel.umd.js|327.05 KiB |76.63 KiB|
|dist/vue-slick-carousel.common.js|326.64 KiB|76.50 KiB|
|dist/vue-slick-carousel-theme.css|4.24 KiB|1.96 KiB|
|dist/vue-slick-carousel.css|1.57 KiB|0.51 KiB|

### CODE REVIEW

**Comment by RasmusO95** [comment]
Why not just use lodash-es? It has the tree shaking you need

**Comment by ekanant** [comment]
> Why not just use lodash-es? It has the tree shaking you need

Ok, I will try. I have not use lodash-es before. Thanks @RasmusO95

**Comment by ekanant** [comment]
> Why not just use lodash-es? It has the tree shaking you need

I try to use lodash-es but size is bigger than lodash.[module]
```
"lodash-es": "^4.17.15",
```

```
import pick from 'lodash-es/pick'
import assign from 'lodash-es/assign'
import get from 'lodash-es/get'
```
|File|Size|Gzipped|
|-|:-:|-:|
|dist/vue-slick-carousel.umd.min.js|99.07 KiB|32.93 KiB|
|dist/vue-slick-carousel.umd.js|345.73 KiB|77.17 KiB|
|dist/vue-slick-carousel.common.js|345.32 KiB|77.03 KiB|
|dist/vue-slick-carousel-theme.css|4.24 KiB|1.96 KiB|
|dist/vue-slick-carousel.css|1.57 KiB|0.51 KiB|

**Comment by kyuwoo-choi** [comment]
Thanks for the PR :tada:
confirmed it reduce the bundle size :)
merging it.

**Pull request merged**
